#!/bin/bash

echo "running check-ruby-debug hook"
checks=("byebug" "binding.b" "binding.break" "debugger")

git diff --cached --name-status | while read flag file; do
	if [ "$flag" == 'D' ]; then continue; fi
  if [ "$file" == 'Gemfile' ]; then continue; fi
  if [ "$file" == 'Gemfile.lock' ]; then continue; fi

	for word in ${checks[@]}; do
		if egrep -q "$word" "$file"; then
			echo "ERROR: Disallowed expression \"${word}\" in file: ${file}" >&2
			exit 1
		fi
	done
done
